### ISSUE TITLE
Big Bug!!!! Needs fixed

### ISSUE THREAD

**Issue by MDeter98** [nixafblawebdesign/nixafblawebdesign.github.io#12]
The user interface does not load correctly.

**Comment by ryanknutson** [comment]
Turns out it's a problem with Github. I contacted their support about it. The css is not loading right.

**Comment by MDeter98** [comment]
👌 thanks

**Comment by ryanknutson** [comment]
This was fixed in e5d8f514356914109ad68c231cd6de7296979c92.
